In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(pd.__version__)

Matplotlib is building the font cache; this may take a moment.

3.0.5

In [6]:
from pathlib import Path

ROOT = Path("..")

RAW_DATA = ROOT / "data" / "raw"

PROCESSED_DATA = ROOT / "data" / "processed"

print(RAW_DATA)

../data/raw

In [7]:
print("Files in raw data folder:\n")

for file in RAW_DATA.iterdir():
    print(file.name)

Files in raw data folder:

soi.txt
iod.csv
nino4.csv
nino34.csv
nino3.csv

In [13]:
DATA_FILES = {
    "nino34": "nino34.csv",   
    "nino3": "nino3.csv",
    "nino4": "nino4.csv",
    "iod": "iod.csv",
}

In [9]:
datasets = {}

for name, filename in DATA_FILES.items():

    file_path = RAW_DATA / filename

    datasets[name] = pd.read_csv(file_path)

print("Datasets Loaded Successfully!")

print(datasets.keys())

Datasets Loaded Successfully!
dict_keys(['nino34', 'nino3', 'nino4', 'iod', 'soi'])

In [12]:
def inspect_dataset(name, df):

    print("=" * 70)
    print(name.upper())
    print("=" * 70)

    print(f"Shape : {df.shape}")

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nFirst Five Rows:")
    display(df.head())

    print("\n")

for name, df in datasets.items():

    inspect_dataset(name, df)

======================================================================
NINO34
======================================================================
Shape : (948, 2)

Columns:
['Date', '   Nino Anom 3.4 Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/']

Data Types:
Date                                                                                                                           str
   Nino Anom 3.4 Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/    float64
dtype: object

Missing Values:
Date                                                                                                                       0
   Nino Anom 3.4 Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/    0
dtype: int64

First Five Rows:

,Date,Nino Anom 3.4 Index using NOAA ERSST v6 from NCEI missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
0,1948-01-01,-9999.0
1,1948-02-01,-9999.0
2,1948-03-01,-9999.0
3,1948-04-01,-9999.0
4,1948-05-01,-9999.0

======================================================================
NINO3
======================================================================
Shape : (948, 2)

Columns:
['Date', '   Nino 3 Anom Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/']

Data Types:
Date                                                                                                                         str
   Nino 3 Anom Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/    float64
dtype: object

Missing Values:
Date                                                                                                                     0
   Nino 3 Anom Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/    0
dtype: int64

First Five Rows:

,Date,Nino 3 Anom Index using NOAA ERSST v6 from NCEI missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
0,1948-01-01,-9999.0
1,1948-02-01,-9999.0
2,1948-03-01,-9999.0
3,1948-04-01,-9999.0
4,1948-05-01,-9999.0

======================================================================
NINO4
======================================================================
Shape : (948, 2)

Columns:
['Date', '   Nino 4 Anom Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/']

Data Types:
Date                                                                                                                         str
   Nino 4 Anom Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/    float64
dtype: object

Missing Values:
Date                                                                                                                     0
   Nino 4 Anom Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/    0
dtype: int64

First Five Rows:

,Date,Nino 4 Anom Index using NOAA ERSST v6 from NCEI missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
0,1948-01-01,-9999.0
1,1948-02-01,-9999.0
2,1948-03-01,-9999.0
3,1948-04-01,-9999.0
4,1948-05-01,-9999.0

======================================================================
IOD
======================================================================
Shape : (1872, 2)

Columns:
['Date', ' DMI HadISST1.1  missing value -9999 https://psl.noaa.gov/data/timeseries/month/']

Data Types:
Date                                                                                    str
 DMI HadISST1.1  missing value -9999 https://psl.noaa.gov/data/timeseries/month/    float64
dtype: object

Missing Values:
Date                                                                                0
 DMI HadISST1.1  missing value -9999 https://psl.noaa.gov/data/timeseries/month/    0
dtype: int64

First Five Rows:

,Date,DMI HadISST1.1 missing value -9999 https://psl.noaa.gov/data/timeseries/month/
0,1870-01-01,-0.438
1,1870-02-01,-0.336
2,1870-03-01,0.177
3,1870-04-01,-0.048
4,1870-05-01,-0.480

======================================================================
SOI
======================================================================
Shape : (165, 1)

Columns:
['(STAND TAHITI - STAND DARWIN)  SEA LEVEL PRESS                                  ']

Data Types:
(STAND TAHITI - STAND DARWIN)  SEA LEVEL PRESS                                      str
dtype: object

Missing Values:
(STAND TAHITI - STAND DARWIN)  SEA LEVEL PRESS                                      0
dtype: int64

First Five Rows:

  (STAND TAHITI - STAND DARWIN)  SEA LEVEL PRESS
0                          ANOMALY               ...
1  YEAR   JAN   FEB   MAR   APR   MAY   JUN   JUL...
2  1951   2.5   1.5  -0.2  -0.5  -1.1   0.3  -1.7...
3  1952  -1.5  -1.0   0.9  -0.4   1.2   1.2   0.8...
4  1953   0.5  -0.8  -0.3   0.3  -2.8   0.2  -0.0...

In [14]:
def inspect(name, df):

    print("="*60)
    print(name.upper())
    print("="*60)

    print(df.head())

    print()

    print(df.info())

    print()

    print(df.describe(include="all"))

for name, df in datasets.items():
    inspect(name, df)

============================================================
NINO34
============================================================
         Date  \
0  1948-01-01
1  1948-02-01
2  1948-03-01
3  1948-04-01
4  1948-05-01

      Nino Anom 3.4 Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
0                                            -9999.0
1                                            -9999.0
2                                            -9999.0
3                                            -9999.0
4                                            -9999.0

<class 'pandas.DataFrame'>
RangeIndex: 948 entries, 0 to 947
Data columns (total 2 columns):
 #   Column                                                                                                                   Non-Null Count  Dtype
---  ------                                                                                                                   --------------  -----
 0   Date                                                                                                                     948 non-null    str
 1      Nino Anom 3.4 Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/  948 non-null    float64
dtypes: float64(1), str(1)
memory usage: 14.9 KB
None

              Date  \
count          948
unique         948
top     1948-01-01
freq             1
mean           NaN
std            NaN
min            NaN
25%            NaN
50%            NaN
75%            NaN
max            NaN

           Nino Anom 3.4 Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
count                                          948.000000
unique                                                NaN
top                                                   NaN
freq                                                  NaN
mean                                          -316.592426
std                                           1751.265040
min                                          -9999.000000
25%                                             -0.860000
50%                                             -0.280000
75%                                              0.342500
max                                              2.720000
============================================================
NINO3
============================================================
         Date  \
0  1948-01-01
1  1948-02-01
2  1948-03-01
3  1948-04-01
4  1948-05-01

      Nino 3 Anom Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
0                                            -9999.0
1                                            -9999.0
2                                            -9999.0
3                                            -9999.0
4                                            -9999.0

<class 'pandas.DataFrame'>
RangeIndex: 948 entries, 0 to 947
Data columns (total 2 columns):
 #   Column                                                                                                                 Non-Null Count  Dtype
---  ------                                                                                                                 --------------  -----
 0   Date                                                                                                                   948 non-null    str
 1      Nino 3 Anom Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/  948 non-null    float64
dtypes: float64(1), str(1)
memory usage: 14.9 KB
None

              Date  \
count          948
unique         948
top     1948-01-01
freq             1
mean           NaN
std            NaN
min            NaN
25%            NaN
50%            NaN
75%            NaN
max            NaN

           Nino 3 Anom Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
count                                          948.000000
unique                                                NaN
top                                                   NaN
freq                                                  NaN
mean                                          -316.620359
std                                           1751.260003
min                                          -9999.000000
25%                                             -0.870000
50%                                             -0.330000
75%                                              0.270000
max                                              3.300000
============================================================
NINO4
============================================================
         Date  \
0  1948-01-01
1  1948-02-01
2  1948-03-01
3  1948-04-01
4  1948-05-01

      Nino 4 Anom Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
0                                            -9999.0
1                                            -9999.0
2                                            -9999.0
3                                            -9999.0
4                                            -9999.0

<class 'pandas.DataFrame'>
RangeIndex: 948 entries, 0 to 947
Data columns (total 2 columns):
 #   Column                                                                                                                 Non-Null Count  Dtype
---  ------                                                                                                                 --------------  -----
 0   Date                                                                                                                   948 non-null    str
 1      Nino 4 Anom Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/  948 non-null    float64
dtypes: float64(1), str(1)
memory usage: 14.9 KB
None

              Date  \
count          948
unique         948
top     1948-01-01
freq             1
mean           NaN
std            NaN
min            NaN
25%            NaN
50%            NaN
75%            NaN
max            NaN

           Nino 4 Anom Index  using NOAA ERSST v6 from NCEI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
count                                          948.000000
unique                                                NaN
top                                                   NaN
freq                                                  NaN
mean                                          -316.658270
std                                           1751.253052
min                                          -9999.000000
25%                                             -0.780000
50%                                             -0.230000
75%                                              0.230000
max                                              1.540000
============================================================
IOD
============================================================
         Date  \
0  1870-01-01
1  1870-02-01
2  1870-03-01
3  1870-04-01
4  1870-05-01

    DMI HadISST1.1  missing value -9999 https://psl.noaa.gov/data/timeseries/month/
0                                             -0.438
1                                             -0.336
2                                              0.177
3                                             -0.048
4                                             -0.480

<class 'pandas.DataFrame'>
RangeIndex: 1872 entries, 0 to 1871
Data columns (total 2 columns):
 #   Column                                                                            Non-Null Count  Dtype
---  ------                                                                            --------------  -----
 0   Date                                                                              1872 non-null   str
 1    DMI HadISST1.1  missing value -9999 https://psl.noaa.gov/data/timeseries/month/  1872 non-null   float64
dtypes: float64(1), str(1)
memory usage: 29.4 KB
None

              Date  \
count         1872
unique        1872
top     1870-01-01
freq             1
mean           NaN
std            NaN
min            NaN
25%            NaN
50%            NaN
75%            NaN
max            NaN

         DMI HadISST1.1  missing value -9999 https://psl.noaa.gov/data/timeseries/month/
count                                         1872.000000
unique                                                NaN
top                                                   NaN
freq                                                  NaN
mean                                           -42.963472
std                                            652.416010
min                                          -9999.000000
25%                                             -0.455750
50%                                             -0.246000
75%                                             -0.025500
max                                              1.279000
============================================================
SOI
============================================================
  (STAND TAHITI - STAND DARWIN)  SEA LEVEL PRESS
0                          ANOMALY               ...
1  YEAR   JAN   FEB   MAR   APR   MAY   JUN   JUL...
2  1951   2.5   1.5  -0.2  -0.5  -1.1   0.3  -1.7...
3  1952  -1.5  -1.0   0.9  -0.4   1.2   1.2   0.8...
4  1953   0.5  -0.8  -0.3   0.3  -2.8   0.2  -0.0...

<class 'pandas.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 1 columns):
 #   Column                                                                            Non-Null Count  Dtype
---  ------                                                                            --------------  -----
 0   (STAND TAHITI - STAND DARWIN)  SEA LEVEL PRESS                                    165 non-null    str
dtypes: str(1)
memory usage: 1.4 KB
None

       (STAND TAHITI - STAND DARWIN)  SEA LEVEL PRESS
count                                                 165
unique                                                160
top     YEAR   JAN   FEB   MAR   APR   MAY   JUN   JUL...
freq                                                    2

In [17]:
def clean_csv_dataset(df, column_name):

    df = df.copy()

    df.columns = ["Date", column_name]

    df["Date"] = pd.to_datetime(df["Date"])

    df[column_name] = pd.to_numeric(df[column_name], errors="coerce")

    df[column_name] = df[column_name].replace(
        [-9999, -9999.0, -99.99],
        np.nan
    )

    df = df.sort_values("Date")

    df.reset_index(drop=True, inplace=True)

    return df
datasets["nino34"] = clean_csv_dataset(
    datasets["nino34"],
    "nino34"
)

datasets["nino3"] = clean_csv_dataset(
    datasets["nino3"],
    "nino3"
)

datasets["nino4"] = clean_csv_dataset(
    datasets["nino4"],
    "nino4"
)

datasets["iod"] = clean_csv_dataset(
    datasets["iod"],
    "iod"
)
datasets["nino34"].head()

        Date  nino34
0 1948-01-01     NaN
1 1948-02-01     NaN
2 1948-03-01     NaN
3 1948-04-01     NaN
4 1948-05-01     NaN

In [ ]:
soi_file = RAW_DATA / "soi.txt"

with open(soi_file, "r") as f:
    lines = f.readlines()

print(len(lines))

168
85 STANDARDIZED    DATA

In [23]:
#parsing soi data
months = [
    "JAN", "FEB", "MAR", "APR", "MAY", "JUN",
    "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"
]

# Find where the standardized table begins
start_idx = None

for i, line in enumerate(lines):
    if "STANDARDIZED" in line.upper():
        start_idx = i
        break

if start_idx is None:
    raise ValueError("STANDARDIZED DATA section not found.")

# Find the YEAR header after STANDARDIZED
year_header = None

for i in range(start_idx, len(lines)):
    if lines[i].strip().startswith("YEAR"):
        year_header = i
        break

if year_header is None:
    raise ValueError("YEAR header not found.")

records = []

# Actual data starts after YEAR header
for line in lines[year_header + 1:]:

    line = line.strip()

    if not line:
        continue

    parts = line.split()

    # Stop when table ends
    if len(parts) != 13 or not parts[0].isdigit():
        break

    year = int(parts[0])

    for month_num, value in enumerate(parts[1:], start=1):

        value = float(value)

        if value == -999.9:
            value = np.nan

        records.append([
            pd.Timestamp(year=year, month=month_num, day=1),
            value
        ])

soi = pd.DataFrame(records, columns=["Date", "soi"])
print(soi.shape)

display(soi.head())

display(soi.tail())

print(soi.isna().sum())

(900, 2)

        Date  soi
0 1951-01-01  1.5
1 1951-02-01  0.9
2 1951-03-01 -0.1
3 1951-04-01 -0.3
4 1951-05-01 -0.7

          Date  soi
895 2025-08-01  0.4
896 2025-09-01  0.0
897 2025-10-01  1.1
898 2025-11-01  1.1
899 2025-12-01 -0.0

Date    0
soi     0
dtype: int64

In [25]:
#mergin all datasets
master = datasets["nino34"].copy()

for dataset in ["nino3", "nino4", "iod"]:
    master = master.merge(
        datasets[dataset],
        on="Date",
        how="outer"
    )

master = master.merge(
    soi,
    on="Date",
    how="outer"
)

master = master.sort_values("Date").reset_index(drop=True)
master.info()

display(master.head())

display(master.tail())

master.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1884 entries, 0 to 1883
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1884 non-null   datetime64[us]
 1   nino34  918 non-null    float64
 2   nino3   918 non-null    float64
 3   nino4   918 non-null    float64
 4   iod     1864 non-null   float64
 5   soi     900 non-null    float64
dtypes: datetime64[us](1), float64(5)
memory usage: 88.4 KB

        Date  nino34  nino3  nino4    iod  soi
0 1870-01-01     NaN    NaN    NaN -0.438  NaN
1 1870-02-01     NaN    NaN    NaN -0.336  NaN
2 1870-03-01     NaN    NaN    NaN  0.177  NaN
3 1870-04-01     NaN    NaN    NaN -0.048  NaN
4 1870-05-01     NaN    NaN    NaN -0.480  NaN

           Date  nino34  nino3  nino4  iod  soi
1879 2026-08-01     NaN    NaN    NaN  NaN  NaN
1880 2026-09-01     NaN    NaN    NaN  NaN  NaN
1881 2026-10-01     NaN    NaN    NaN  NaN  NaN
1882 2026-11-01     NaN    NaN    NaN  NaN  NaN
1883 2026-12-01     NaN    NaN    NaN  NaN  NaN

,Date,nino34,nino3,nino4,iod,soi
count,1884,918.000000,918.000000,918.000000,1864.000000,900.000000
mean,1948-06-16 06:35:55.414013,-0.173878,-0.202723,-0.241874,-0.233702,0.154556
min,1870-01-01 00:00:00,-2.450000,-2.400000,-2.210000,-1.634000,-3.600000
25%,1909-03-24 06:00:00,-0.780000,-0.820000,-0.720000,-0.452250,-0.400000
50%,1948-06-16 00:00:00,-0.250000,-0.300000,-0.190000,-0.245000,0.200000
75%,1987-09-08 12:00:00,0.357500,0.300000,0.250000,-0.024000,0.800000
max,2026-12-01 00:00:00,2.720000,3.300000,1.540000,1.279000,2.900000
std,NaN,0.871854,0.903206,0.690128,0.346221,0.933704

In [26]:
#saving 
master.to_csv(
    PROCESSED_DATA / "master_enso_monthly.csv",
    index=False
)